version: '2'
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
services:
  dns-server:
    build: ./dns-server
    container_name: 'dns-server'
    networks:
      frontend:
        ipv4_address: 172.20.0.2
    ports:
      - "172.20.0.1:53:53/udp"
    dns:
      - 172.20.0.2
    command: /bin/bash -c "
      /etc/init.d/bind9 start &&
      while :; do sleep 10; done
      "
  nginx:
    # image: nginx
    image: nginxproxy/nginx-proxy:alpine
    container_name: 'nginx'
    networks:
      frontend:
        ipv4_address: 172.20.0.3
      backend:
    dns:
      - 172.20.0.2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - ./nginx/ssl/certs/nginx.crt:/etc/ssl/certs/nginx.crt
      - ./nginx/ssl/private/nginx.key:/etc/ssl/private/nginx.key
    ports:
      - 80:80
      - 443:443
  mongo:
    image: mongo:3
    container_name: 'mongo-db'
    volumes:
      - ./mongo/data:/db/data
    networks:
      backend:
        ipv4_address: 172.30.0.4
    ports:
      - '27017:27017'
  api:
    build: ./parse-server
    container_name: 'parse-server'
    networks:
      backend:
        ipv4_address: 172.30.0.5
    ports:
      - '1337:1337'
    environment:
      PORT: 1337
      DATABASE_URI: mongodb://mongo:27017
      APP_ID: 'web-app-docker'
      MASTER_KEY: 'master'
      PARSE_MOUNT: '/parse'
      SERVER_URL: 'http://172.30.0.5:1337/parse'
    volumes:
      - ./parse-server/cloud:/parse/cloud
      - ./parse-server/public:/parse/public
    depends_on:
      - mongo
  dashboard:
    build: ./dashboard
    container_name: "parse-dashboard"
    networks:
      backend:
        ipv4_address: 172.30.0.6
    ports:
      - "4040:4040"
    environment:
      PORT: 4040
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: "True"
      PARSE_DASHBOARD_SERVER_URL: 'http://172.30.0.5:1337/parse'
      PARSE_DASHBOARD_MASTER_KEY: "master"
      PARSE_DASHBOARD_APP_ID: "web-app-docker"
      PARSE_DASHBOARD_APP_NAME: "Docker Web App"
      PARSE_DASHBOARD_USER_ID: "user"
      PARSE_DASHBOARD_USER_PASSWORD: "password"
  web-app:
    build: ./web-app
    container_name: "web-app"
    networks:
      backend:
        ipv4_address: 172.30.0.7
    ports:
      - "3000:3000"
